/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({

});

Ext.application({
    views: [
        'Login'
    ],
    name: 'FB',
    startupImage: {
        '320x460': 'resources/loading/Homescreen.jpg',
        '768x1004': 'resources/loading/Homescreen~ipad.jpg'
    },

    launch: function() {

        Ext.create('FB.view.Login', {fullscreen: true});
    }

});
